// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Mark Wells <contact@markwells.dev>

//! Config template generation for `catenary config`.

#![allow(clippy::print_stdout, reason = "CLI tool needs to output to stdout")]

/// Annotated recommended config template.
///
/// This is a curated TOML document with comments explaining each entry,
/// not generated from structs. Users redirect this to their config file.
/// The target path depends on `XDG_CONFIG_HOME` (Linux: `~/.config`,
/// macOS: `~/Library/Application Support`, Windows: `AppData/Roaming`).
const TEMPLATE: &str = r#"# Catenary recommended config
# Generated by `catenary config`. Edit to match your workflow.
#
# Config sources (later overrides earlier):
#   1. <XDG_CONFIG_HOME>/catenary/config.toml  (this file)
#   2. .catenary.toml                          (project-local, searched upward)
#   3. CATENARY_CONFIG env var                 (explicit override)
#
# XDG_CONFIG_HOME defaults:
#   Linux:   ~/.config
#   macOS:   ~/Library/Application Support
#   Windows: C:\Users\<user>\AppData\Roaming

# ── Command filtering ────────────────────────────────────────────
#
# Denied commands are blocked in Bash/shell tool calls. Each entry
# maps a command name to a guidance message shown to the agent.
# Template variables like {read} resolve to tool names per-client.
#
# Two sections:
#   [commands.deny]            — blocked at any pipeline position
#   [commands.deny_when_first] — blocked at position 0, allowed
#                                mid-pipeline (reading from stdin)

[commands.deny]
# File reading — use the host's Read tool instead
cat = "Use {read} instead"
less = "Use {read} instead"
more = "Use {read} instead"

# Text search — use Catenary's LSP-backed grep instead
rg = "Use {catenary_grep} instead"
ag = "Use {catenary_grep} instead"
ack = "Use {catenary_grep} instead"
fd = "Use {catenary_grep} instead"
rgrep = "Use {catenary_grep} instead"
zgrep = "Use {catenary_grep} instead"

# Directory listing — use Catenary's glob instead
ls = "Use {catenary_glob} instead"
dir = "Use {catenary_glob} instead"
tree = "Use {catenary_glob} instead"
find = "Use {catenary_glob} instead"

# Git subcommands that duplicate Catenary tools
"git ls-files" = "Use {catenary_glob} instead"
"git ls-tree" = "Use {catenary_glob} instead"

# Project-specific: uncomment if your project uses make
# cargo = "Use make instead, suggest a target if needed"
# rustc = "Use make instead, suggest a target if needed"
# rustup = "Use make instead, suggest a target if needed"

[commands.deny_when_first]
# Pipeline-safe commands: denied at position 0 (reading files),
# allowed mid-pipeline (reading from stdin).
grep = "Use {catenary_grep} instead"
egrep = "Use {catenary_grep} instead"
fgrep = "Use {catenary_grep} instead"
head = "Use {read} instead"
tail = "Use {read} instead"
sed = "Use {edit} instead"
"git grep" = "Use {catenary_grep} instead"

# ── Project-local overrides (.catenary.toml) ─────────────────────
#
# Project config amends the user config by default. Examples:
#
#   # Deny additional commands for this project
#   [commands.deny]
#   cargo = "Use make instead, suggest a target if needed"
#
#   # Allow a command denied in the user config
#   [commands.allow]
#   find = true
#
#   # Replace the user's command set entirely
#   [commands]
#   inherit = false
#
#   [commands.deny]
#   cargo = "Use make instead, suggest a target if needed"

# ── Notifications ────────────────────────────────────────────────
#
# Controls which events are promoted to user-facing notifications
# via systemMessage. Options: "debug", "info", "warn", "error".

# [notifications]
# threshold = "warn"

# ── Tool budgets ─────────────────────────────────────────────────
#
# Output budgets in characters. Larger budgets give the agent more
# context but consume more of the conversation window.

# [tools.grep]
# budget = 4000

# [tools.glob]
# budget = 2000
# maps_threshold = 200
"#;

/// Print the recommended config template to stdout.
pub fn print_template() {
    print!("{TEMPLATE}");
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    reason = "tests use expect for readable assertions"
)]
mod tests {
    use super::*;

    #[test]
    fn template_is_valid_toml() {
        // TOML supports `#` comments natively, so the full template
        // (including commented-out examples) should parse as-is.
        // Use `toml::from_str` (document parser), not `str::parse`
        // (single-value parser).
        toml::from_str::<toml::Value>(TEMPLATE).expect("template should be valid TOML");
    }

    #[test]
    fn template_contains_deny_sections() {
        assert!(
            TEMPLATE.contains("[commands.deny]"),
            "template should contain [commands.deny]",
        );
        assert!(
            TEMPLATE.contains("[commands.deny_when_first]"),
            "template should contain [commands.deny_when_first]",
        );
    }

    #[test]
    fn template_contains_template_variables() {
        assert!(
            TEMPLATE.contains("{read}"),
            "template should contain {{read}} variable",
        );
        assert!(
            TEMPLATE.contains("{catenary_grep}"),
            "template should contain {{catenary_grep}} variable",
        );
        assert!(
            TEMPLATE.contains("{catenary_glob}"),
            "template should contain {{catenary_glob}} variable",
        );
        assert!(
            TEMPLATE.contains("{edit}"),
            "template should contain {{edit}} variable",
        );
    }
}
