/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_fn = 1,
  anon_sym_struct = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_identifier = 5,
  sym_content = 6,
  sym_source_file = 7,
  sym__definition = 8,
  sym_function_definition = 9,
  sym_struct_definition = 10,
  sym_block = 11,
  sym__block_item = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_block_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_content] = "content",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_struct_definition] = "struct_definition",
  [sym_block] = "block",
  [sym__block_item] = "_block_item",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_content] = sym_content,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_struct_definition] = sym_struct_definition,
  [sym_block] = sym_block,
  [sym__block_item] = sym__block_item,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__block_item] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 14,
  [18] = 15,
  [19] = 16,
  [20] = 13,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == 'f') ADVANCE(9);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == '{') ADVANCE(5);
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 1:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'c') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 't') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'u') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym__definition] = STATE(8),
    [sym_function_definition] = STATE(8),
    [sym_struct_definition] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
    [anon_sym_struct] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_struct_definition] = STATE(3),
    [sym__block_item] = STATE(3),
    [aux_sym_block_repeat1] = STATE(3),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(13),
    [sym_content] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_struct_definition] = STATE(4),
    [sym__block_item] = STATE(4),
    [aux_sym_block_repeat1] = STATE(4),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(17),
    [sym_content] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__definition] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_struct_definition] = STATE(4),
    [sym__block_item] = STATE(4),
    [aux_sym_block_repeat1] = STATE(4),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(24),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_content] = ACTIONS(29),
  },
  [STATE(5)] = {
    [sym__definition] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_struct_definition] = STATE(6),
    [sym__block_item] = STATE(6),
    [aux_sym_block_repeat1] = STATE(6),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(32),
    [sym_content] = ACTIONS(34),
  },
  [STATE(6)] = {
    [sym__definition] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_struct_definition] = STATE(4),
    [sym__block_item] = STATE(4),
    [aux_sym_block_repeat1] = STATE(4),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_struct] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(36),
    [sym_content] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_fn,
    ACTIONS(43), 1,
      anon_sym_struct,
    STATE(7), 4,
      sym__definition,
      sym_function_definition,
      sym_struct_definition,
      aux_sym_source_file_repeat1,
  [16] = 4,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(7), 1,
      anon_sym_struct,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(7), 4,
      sym__definition,
      sym_function_definition,
      sym_struct_definition,
      aux_sym_source_file_repeat1,
  [32] = 4,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym_content,
    STATE(14), 1,
      sym_block,
    ACTIONS(48), 3,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_RBRACE,
  [47] = 4,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_content,
    STATE(16), 1,
      sym_block,
    ACTIONS(54), 3,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_RBRACE,
  [62] = 3,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
    ACTIONS(48), 3,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_struct,
  [74] = 3,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_block,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_struct,
  [86] = 2,
    ACTIONS(62), 1,
      sym_content,
    ACTIONS(60), 3,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_RBRACE,
  [95] = 2,
    ACTIONS(66), 1,
      sym_content,
    ACTIONS(64), 3,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_RBRACE,
  [104] = 2,
    ACTIONS(70), 1,
      sym_content,
    ACTIONS(68), 3,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_RBRACE,
  [113] = 2,
    ACTIONS(74), 1,
      sym_content,
    ACTIONS(72), 3,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_RBRACE,
  [122] = 1,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_struct,
  [128] = 1,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_struct,
  [134] = 1,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_struct,
  [140] = 1,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_struct,
  [146] = 1,
    ACTIONS(76), 1,
      sym_identifier,
  [150] = 1,
    ACTIONS(78), 1,
      sym_identifier,
  [154] = 1,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
  [158] = 1,
    ACTIONS(82), 1,
      sym_identifier,
  [162] = 1,
    ACTIONS(84), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 16,
  [SMALL_STATE(9)] = 32,
  [SMALL_STATE(10)] = 47,
  [SMALL_STATE(11)] = 62,
  [SMALL_STATE(12)] = 74,
  [SMALL_STATE(13)] = 86,
  [SMALL_STATE(14)] = 95,
  [SMALL_STATE(15)] = 104,
  [SMALL_STATE(16)] = 113,
  [SMALL_STATE(17)] = 122,
  [SMALL_STATE(18)] = 128,
  [SMALL_STATE(19)] = 134,
  [SMALL_STATE(20)] = 140,
  [SMALL_STATE(21)] = 146,
  [SMALL_STATE(22)] = 150,
  [SMALL_STATE(23)] = 154,
  [SMALL_STATE(24)] = 158,
  [SMALL_STATE(25)] = 162,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [80] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mock(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mock",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
